//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguros.Falabella.Application.ServiceSale {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sale", Namespace="http://schemas.datacontract.org/2004/07/SegurosFalabellaEntity")]
    [System.SerializableAttribute()]
    public partial class Sale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cust_ccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime cust_dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cust_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cust_phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prod_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prod_featuresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prod_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prod_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sale_assistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sale_coverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sale_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal sale_primaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_address {
            get {
                return this.cust_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_addressField, value) != true)) {
                    this.cust_addressField = value;
                    this.RaisePropertyChanged("cust_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cust_cc {
            get {
                return this.cust_ccField;
            }
            set {
                if ((this.cust_ccField.Equals(value) != true)) {
                    this.cust_ccField = value;
                    this.RaisePropertyChanged("cust_cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_city {
            get {
                return this.cust_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_cityField, value) != true)) {
                    this.cust_cityField = value;
                    this.RaisePropertyChanged("cust_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime cust_dateOfBirth {
            get {
                return this.cust_dateOfBirthField;
            }
            set {
                if ((this.cust_dateOfBirthField.Equals(value) != true)) {
                    this.cust_dateOfBirthField = value;
                    this.RaisePropertyChanged("cust_dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cust_id {
            get {
                return this.cust_idField;
            }
            set {
                if ((this.cust_idField.Equals(value) != true)) {
                    this.cust_idField = value;
                    this.RaisePropertyChanged("cust_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_lastName {
            get {
                return this.cust_lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_lastNameField, value) != true)) {
                    this.cust_lastNameField = value;
                    this.RaisePropertyChanged("cust_lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_name {
            get {
                return this.cust_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_nameField, value) != true)) {
                    this.cust_nameField = value;
                    this.RaisePropertyChanged("cust_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cust_phone {
            get {
                return this.cust_phoneField;
            }
            set {
                if ((this.cust_phoneField.Equals(value) != true)) {
                    this.cust_phoneField = value;
                    this.RaisePropertyChanged("cust_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prod_code {
            get {
                return this.prod_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.prod_codeField, value) != true)) {
                    this.prod_codeField = value;
                    this.RaisePropertyChanged("prod_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prod_features {
            get {
                return this.prod_featuresField;
            }
            set {
                if ((object.ReferenceEquals(this.prod_featuresField, value) != true)) {
                    this.prod_featuresField = value;
                    this.RaisePropertyChanged("prod_features");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prod_id {
            get {
                return this.prod_idField;
            }
            set {
                if ((this.prod_idField.Equals(value) != true)) {
                    this.prod_idField = value;
                    this.RaisePropertyChanged("prod_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prod_name {
            get {
                return this.prod_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.prod_nameField, value) != true)) {
                    this.prod_nameField = value;
                    this.RaisePropertyChanged("prod_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sale_assistance {
            get {
                return this.sale_assistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.sale_assistanceField, value) != true)) {
                    this.sale_assistanceField = value;
                    this.RaisePropertyChanged("sale_assistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sale_coverage {
            get {
                return this.sale_coverageField;
            }
            set {
                if ((object.ReferenceEquals(this.sale_coverageField, value) != true)) {
                    this.sale_coverageField = value;
                    this.RaisePropertyChanged("sale_coverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sale_id {
            get {
                return this.sale_idField;
            }
            set {
                if ((this.sale_idField.Equals(value) != true)) {
                    this.sale_idField = value;
                    this.RaisePropertyChanged("sale_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal sale_prima {
            get {
                return this.sale_primaField;
            }
            set {
                if ((this.sale_primaField.Equals(value) != true)) {
                    this.sale_primaField = value;
                    this.RaisePropertyChanged("sale_prima");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/SegurosFalabellaEntity")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cust_ccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime cust_dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cust_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cust_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cust_phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_address {
            get {
                return this.cust_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_addressField, value) != true)) {
                    this.cust_addressField = value;
                    this.RaisePropertyChanged("cust_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cust_cc {
            get {
                return this.cust_ccField;
            }
            set {
                if ((this.cust_ccField.Equals(value) != true)) {
                    this.cust_ccField = value;
                    this.RaisePropertyChanged("cust_cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_city {
            get {
                return this.cust_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_cityField, value) != true)) {
                    this.cust_cityField = value;
                    this.RaisePropertyChanged("cust_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime cust_dateOfBirth {
            get {
                return this.cust_dateOfBirthField;
            }
            set {
                if ((this.cust_dateOfBirthField.Equals(value) != true)) {
                    this.cust_dateOfBirthField = value;
                    this.RaisePropertyChanged("cust_dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cust_id {
            get {
                return this.cust_idField;
            }
            set {
                if ((this.cust_idField.Equals(value) != true)) {
                    this.cust_idField = value;
                    this.RaisePropertyChanged("cust_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_lastName {
            get {
                return this.cust_lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_lastNameField, value) != true)) {
                    this.cust_lastNameField = value;
                    this.RaisePropertyChanged("cust_lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cust_name {
            get {
                return this.cust_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.cust_nameField, value) != true)) {
                    this.cust_nameField = value;
                    this.RaisePropertyChanged("cust_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cust_phone {
            get {
                return this.cust_phoneField;
            }
            set {
                if ((this.cust_phoneField.Equals(value) != true)) {
                    this.cust_phoneField = value;
                    this.RaisePropertyChanged("cust_phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSale.ISaleWCF")]
    public interface ISaleWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/SelectSale", ReplyAction="http://tempuri.org/ISaleWCF/SelectSaleResponse")]
        Seguros.Falabella.Application.ServiceSale.Sale[] SelectSale();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/SelectSale", ReplyAction="http://tempuri.org/ISaleWCF/SelectSaleResponse")]
        System.Threading.Tasks.Task<Seguros.Falabella.Application.ServiceSale.Sale[]> SelectSaleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/SelectCustomer", ReplyAction="http://tempuri.org/ISaleWCF/SelectCustomerResponse")]
        Seguros.Falabella.Application.ServiceSale.Customer[] SelectCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/SelectCustomer", ReplyAction="http://tempuri.org/ISaleWCF/SelectCustomerResponse")]
        System.Threading.Tasks.Task<Seguros.Falabella.Application.ServiceSale.Customer[]> SelectCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/SelectSaleId", ReplyAction="http://tempuri.org/ISaleWCF/SelectSaleIdResponse")]
        Seguros.Falabella.Application.ServiceSale.Sale SelectSaleId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/SelectSaleId", ReplyAction="http://tempuri.org/ISaleWCF/SelectSaleIdResponse")]
        System.Threading.Tasks.Task<Seguros.Falabella.Application.ServiceSale.Sale> SelectSaleIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/AddSale", ReplyAction="http://tempuri.org/ISaleWCF/AddSaleResponse")]
        void AddSale(Seguros.Falabella.Application.ServiceSale.Sale Obejto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/AddSale", ReplyAction="http://tempuri.org/ISaleWCF/AddSaleResponse")]
        System.Threading.Tasks.Task AddSaleAsync(Seguros.Falabella.Application.ServiceSale.Sale Obejto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/AddSaleCustomer", ReplyAction="http://tempuri.org/ISaleWCF/AddSaleCustomerResponse")]
        void AddSaleCustomer(Seguros.Falabella.Application.ServiceSale.Sale Obejto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleWCF/AddSaleCustomer", ReplyAction="http://tempuri.org/ISaleWCF/AddSaleCustomerResponse")]
        System.Threading.Tasks.Task AddSaleCustomerAsync(Seguros.Falabella.Application.ServiceSale.Sale Obejto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaleWCFChannel : Seguros.Falabella.Application.ServiceSale.ISaleWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleWCFClient : System.ServiceModel.ClientBase<Seguros.Falabella.Application.ServiceSale.ISaleWCF>, Seguros.Falabella.Application.ServiceSale.ISaleWCF {
        
        public SaleWCFClient() {
        }
        
        public SaleWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Seguros.Falabella.Application.ServiceSale.Sale[] SelectSale() {
            return base.Channel.SelectSale();
        }
        
        public System.Threading.Tasks.Task<Seguros.Falabella.Application.ServiceSale.Sale[]> SelectSaleAsync() {
            return base.Channel.SelectSaleAsync();
        }
        
        public Seguros.Falabella.Application.ServiceSale.Customer[] SelectCustomer() {
            return base.Channel.SelectCustomer();
        }
        
        public System.Threading.Tasks.Task<Seguros.Falabella.Application.ServiceSale.Customer[]> SelectCustomerAsync() {
            return base.Channel.SelectCustomerAsync();
        }
        
        public Seguros.Falabella.Application.ServiceSale.Sale SelectSaleId(int id) {
            return base.Channel.SelectSaleId(id);
        }
        
        public System.Threading.Tasks.Task<Seguros.Falabella.Application.ServiceSale.Sale> SelectSaleIdAsync(int id) {
            return base.Channel.SelectSaleIdAsync(id);
        }
        
        public void AddSale(Seguros.Falabella.Application.ServiceSale.Sale Obejto) {
            base.Channel.AddSale(Obejto);
        }
        
        public System.Threading.Tasks.Task AddSaleAsync(Seguros.Falabella.Application.ServiceSale.Sale Obejto) {
            return base.Channel.AddSaleAsync(Obejto);
        }
        
        public void AddSaleCustomer(Seguros.Falabella.Application.ServiceSale.Sale Obejto) {
            base.Channel.AddSaleCustomer(Obejto);
        }
        
        public System.Threading.Tasks.Task AddSaleCustomerAsync(Seguros.Falabella.Application.ServiceSale.Sale Obejto) {
            return base.Channel.AddSaleCustomerAsync(Obejto);
        }
    }
}
